### ISSUE TITLE
Add support for body in DELETE

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#203]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 23, 2011 16:53:44_

Delete should support body content

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=48_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 01, 2011 03:21:55_

Not supported by HTTPBuilder

java.lang.IllegalArgumentException: Cannot set a request body for a DELETE method
	at groovyx.net.http.HTTPBuilder$RequestConfigDelegate.setBody(HTTPBuilder.java:1144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2395)
	at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3315)
	at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:183)
	at groovy.lang.Closure.setPropertyTryThese(Closure.java:251)
	at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:241)
	at groovy.lang.Closure.setProperty(Closure.java:222)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:531)

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [rus...@gmail.com](https://code.google.com/u/100491685150359683480/) on July 16, 2011 04:11:13_

This is really missing. Would be good to get it fixed in HTTPBuilder or have some workaround.

**Comment by johanhaleby** [comment]
_From [rus...@gmail.com](https://code.google.com/u/100491685150359683480/) on May 02, 2012 16:43:16_

Taking into account that dependency on HTTPBuilder is now gone, can we reopen this ticket?

Most modern REST APIs support batch DELETE operations where body content required.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 02, 2012 23:01:26_

What do you mean by batch DELETE operations? It should be possible to specify a request body for the DELETE method as of version 1.6. It's not supported for multi-part file data uploading but to me it seems awkward to use a DELETE method for that. Correct me if I'm wrong.

**Comment by johanhaleby** [comment]
_From [rus...@gmail.com](https://code.google.com/u/100491685150359683480/) on May 03, 2012 05:24:35_

Should have tested first. Works perfectly in 1.6.1. Thanks!
