### ISSUE TITLE
Rest assured incompatible with javax.servlet under dofilter method

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#241]
_From [vsvarun1...@gmail.com](https://code.google.com/u/118401020174981696421/) on July 22, 2011 08:49:41_

12:14:43,682 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[localhost].[/iMAS/Configurator].[default]] Servlet.service() for servlet default threw exception: java.lang.NoSuchMethodError: org.objectweb.asm.ClassWriter.<init>(I)V
	at org.codehaus.groovy.runtime.callsite.CallSiteGenerator.compileStaticMethod(CallSiteGenerator.java:233) [:1.8.1]
	at org.codehaus.groovy.reflection.CachedMethod.createStaticMetaMethodSite(CachedMethod.java:285) [:1.8.1]
	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.createStaticMetaMethodSite(StaticMetaMethodSite.java:111) [:1.8.1]
	at groovy.lang.MetaClassImpl.createStaticSite(MetaClassImpl.java:3009) [:1.8.1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallStaticSite(CallSiteArray.java:61) [:1.8.1]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:50) [:1.8.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:157) [:1.8.1]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:169) [:1.8.1]
	at com.jayway.restassured.internal.RequestSpecificationImpl.<init>(RequestSpecificationImpl.groovy:68) [:]
	at com.jayway.restassured.RestAssured.createTestSpecification(RestAssured.java:877) [:]
	at com.jayway.restassured.RestAssured.given(RestAssured.java:585) [:]
	at com.jayway.restassured.RestAssured.get(RestAssured.java:615) [:]
	at com.iri.iMAS.configurator.web.filter.MASAuthenticationFilter.doFilter(MASAuthenticationFilter.java:46) [:]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:274) [:6.0.0.Final]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:242) [:6.0.0.Final]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275) [:6.0.0.Final]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191) [:6.0.0.Final]
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:181) [:6.0.0.Final]
	at org.jboss.modcluster.catalina.CatalinaContext$RequestListenerValve.event(CatalinaContext.java:285) [:1.1.0.Final]
	at org.jboss.modcluster.catalina.CatalinaContext$RequestListenerValve.invoke(CatalinaContext.java:261) [:1.1.0.Final]
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:88) [:6.0.0.Final]
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:100) [:6.0.0.Final]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127) [:6.0.0.Final]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102) [:6.0.0.Final]
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158) [:6.0.0.Final]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109) [:6.0.0.Final]
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:53) [:6.0.0.Final]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:362) [:6.0.0.Final]
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877) [:6.0.0.Final]
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:654) [:6.0.0.Final]
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:951) [:6.0.0.Final]
	at java.lang.Thread.run(Unknown Source) [:1.6.0_22]

**Attachment:** [MASAuthenticationFilter.java](http://code.google.com/p/rest-assured/issues/detail?id=86)

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=86_

**Comment by johanhaleby** [comment]
_From [vsvarun1...@gmail.com](https://code.google.com/u/118401020174981696421/) on July 21, 2011 23:54:15_

I am using JBoss AS 6.0
i have put a filter in web.xml which points to MASAuthenticationFilter.java

How to put RestAssured Filter which receives all the request first and then continue to hit appropriate url as we already have it with javax.servlet

i use groovy1.8.1.jar
and all the latest jars

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on August 01, 2011 23:04:06_

It could be that Rest Assured doesn't work with Groovy 1.8. It depends on HTTP Builder which depends on Groovy 1.7. Please download the correct dependencies from the download page and make sure that you have then in classpath.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 01, 2011 00:11:12_

Won't fix due to inactivity from user

**Status:** WontFix
