### ISSUE TITLE
rest-assured parses body (if application/json) even though expect should only verify return code

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#256]
_From [christia...@i-netcompany.com](https://code.google.com/u/103928549623871286729/) on September 07, 2011 17:17:26_

rest-assured gave me the following exception, even though I asked it to verify the statusCode only:
RestAssured.expect().statusCode(200).when().get(url);
(I hope this wasn't my fault)

net.sf.json.JSONException: Invalid JSON String
Exception in thread "main" groovyx.net.http.ResponseParseException: OK
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:143)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:484)
		at com.jayway.restassured.internal.RequestSpecificationImpl$1.super$2$doRequest(RequestSpecificationImpl.groovy)
at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at net.sf.json.groovy.JsonSlurper.parseText(JsonSlurper.java:80)
	at net.sf.json.groovy.JsonSlurper.parse(JsonSlurper.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at groovyx.net.http.ParserRegistry.parseJSON(ParserRegistry.java:266)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:88)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:88)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:923)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:886)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)
	at groovy.lang.Closure.call(Closure.java:282)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:127)
	at groovy.lang.Closure.call(Closure.java:295)
	at com.jayway.restassured.internal.RequestSpecificationImpl$1.doRequest(RequestSpecificationImpl.groovy:492)
	at groovyx.net.http.HTTPBuilder.parseResponse(HTTPBuilder.java:545)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:427)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:478)
	at com.jayway.restassured.internal.RequestSpecificationImpl$1.super$2$doRequest(RequestSpecificationImpl.groovy)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:376)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at groovyx.net.http.HTTPBuilder$request.call(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at java.lang.reflect.Method.invoke(Method.java:616)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:132)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:88)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:542)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendHttpRequest(RequestSpecificationImpl.groovy)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1058)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:127)
	at com.jayway.restassured.internal.RequestSpecificationImpl$1.doRequest(RequestSpecificationImpl.groovy:492)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:427)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:376)
	at groovyx.net.http.HTTPBuilder$request.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:132)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendHttpRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:536)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:542)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendHttpRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendRequest.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendHttpRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:132)
	at com.jayway.restassured.internal.filter.RootFilter.filter(RootFilter.groovy:28)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:536)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:132)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendRequest.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy....

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=102_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 07, 2011 09:17:08_

Hi, 

It looks like a bug indeed. How ever it seems like the server is not returning JSON but something else. But you're right that it shouldn't fail.

Thanks for reporting

**Comment by johanhaleby** [comment]
_From [christia...@i-netcompany.com](https://code.google.com/u/103928549623871286729/) on September 07, 2011 09:33:05_

i think my server is set to reply with Content-type:application/json all the time and in this case it fails, and returns 500 with the exception instead of valid json.  I will try to provide additional info if needed.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 14, 2011 00:51:10_

This has now been fixed in trunk. Please try it out if you like by building rest assured from trunk.

**Status:** Fixed
