### ISSUE TITLE
Wrong Charset when reading the Response  

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#311]
_From [mbue...@gmail.com](https://code.google.com/u/101992249258370510682/) on February 02, 2012 16:21:44_

What steps will reproduce the problem? public void test() throws Exception {
        ResponseBuilder b = new ResponseBuilder();
        b.setHeaders(new Headers());
        b.setBody(new ByteArrayInputStream("äöü".getBytes("UTF-8")));
        b.setStatusCode(200);
        b.setContentType("application/json;charset=UTF-8");
        Response r = b.build();
        // works
        assertEquals("äöü",new String(r.asByteArray(), "UTF-8"));
        
        b = new ResponseBuilder();
        b.setHeaders(new Headers());
        b.setBody(new ByteArrayInputStream("äöü".getBytes("UTF-8")));
        b.setStatusCode(200);
        b.setContentType("application/json;charset=UTF-8");
        r = b.build();
        // uses the Defaultcharset instead of UTF-8 eg. on Windows 1252
        assertEquals("äöü",r.asString());
        
        b = new ResponseBuilder();
        b.setHeaders(new Headers(new Header("charset", "UTF-8")));
        b.setBody(new ByteArrayInputStream("äöü".getBytes("UTF-8")));
        b.setStatusCode(200);
        //b.setContentType("application/json;charset=UTF-8");
        r = b.build();
        /* throws java.lang.NullPointerException: Cannot invoke method close() on null object
        	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
        	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
        	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
        	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
        	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:40)
        	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
        	at com.jayway.restassured.internal.RestAssuredResponseImpl.convertStreamToString(RestAssuredResponseImpl.groovy:343)
        	at com.jayway.restassured.internal.RestAssuredResponseImpl.this$2$convertStreamToString(RestAssuredResponseImpl.groovy)
        	at com.jayway.restassured.internal.RestAssuredResponseImpl$this$2$convertStreamToString.callCurrent(Unknown Source)
        	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:44)
        	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
        	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
        	at com.jayway.restassured.internal.RestAssuredResponseImpl.asString(RestAssuredResponseImpl.groovy:131) 
        */	
        assertEquals("äöü",r.asString());
        
    } What is the expected output? What do you see instead? See the Test. What version of the product are you using? On what operating system? 1.5 on Windows7 64Bit Please provide any additional information below.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=157_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 02, 2012 23:25:57_

Hi, 

This is a known issue and it should be resolved in 1.6-SNAPSHOT. Would you please be so kind and try it out with the new version? If you're using Maven depend on version 1.6-SNAPSHOT and when adding the following repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 02, 2012 23:39:33_

I've ran your test successfully so it seems to work in the new version.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [mbue...@gmail.com](https://code.google.com/u/101992249258370510682/) on February 03, 2012 00:29:44_

Hi,
it works with 1.6-SNAPSHOT. Thank you and keep gooing the good work. I really like rest-assured

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 03, 2012 01:14:22_

Thanks! :)
