### ISSUE TITLE
NPE when calling Response.sessionId() and cookies are null

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#327]
_From [fcamb...@gmail.com](https://code.google.com/u/111948726400665388556/) on May 22, 2012 00:53:28_

What steps will reproduce the problem? 1. Make a REST call on a server, that will return an error (in my case, status=400), this way, no cookies will be returned in the response
2. Try to call response.sessionId() on the Response object : there will be a NPE with following stacktrace :
java.lang.NullPointerException: Cannot invoke method getValue() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:77)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:45)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:32)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at com.jayway.restassured.response.Cookies$getValue.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseImpl.cookie(RestAssuredResponseImpl.groovy:259)
	at com.jayway.restassured.response.Response$cookie.callCurrent(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseImpl.getSessionId(RestAssuredResponseImpl.groovy:291)
	at com.jayway.restassured.internal.RestAssuredResponseImpl.sessionId(RestAssuredResponseImpl.groovy:287)
	at fr.fcamblor.demos.sbjd.test.rules.RequiresDefaultRestAssuredConfiguration$KeepingSessionIdAmongRequestsFilter.filter(RequiresDefaultRestAssuredConfiguration.java:43) What is the expected output? What do you see instead? I would have expected a null sessionId instead of a NPE. What version of the product are you using? On what operating system? Rest Assured 1.6.1 Please provide any additional information below.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=173_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2012 23:16:02_

Thanks for reporting

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 21, 2012 23:26:57_

I've now fixed this in trunk

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [fcamb...@gmail.com](https://code.google.com/u/111948726400665388556/) on May 29, 2012 12:43:32_

I confirm this fixes the NPE prior to 1.6.2

**Comment by ushanaidu20** [comment]
Hi Johan, Can you share the fix for error - java.util.zip.ZipException: incorrect header check
