### ISSUE TITLE
Certificate authentication with own truststore doesn't work

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#359]
_From [henrik.k...@gmail.com](https://code.google.com/u/101552491294560837468/) on November 12, 2012 11:49:19_

What steps will reproduce the problem? 1. Do an request over https to a service with a certificate sign by a CA that's not in default cacerts 2. 3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? 1.7, Windows 7 Please provide any additional information below. Running this test class generates:
javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at com.sun.net.ssl.internal.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:352)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:692)
	at org.apache.http.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:65)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.client.HttpClient$execute.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:1341)
	at com.jayway.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:489)
	at com.jayway.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:438)
	at com.jayway.restassured.internal.http.HTTPBuilder$request.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:917)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendHttpRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendHttpRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:784)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendRequest.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.filter.RootFilter.filter(RootFilter.groovy:28)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:47)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:717)
	at com.jayway.restassured.internal.RequestSpecificationImpl$invokeFilterChain.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1106)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$applyPathParamsAndSendRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:46)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:127)
	at com.jayway.restassured.specification.RequestSender$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.get(ResponseSpecificationImpl.groovy:218)
	at se.pulsencombine.integration.externalservices.RestTestCase.testGetRoot(RestTestCase.java:59)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(Invoke...

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=205_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 12, 2012 12:18:09_

Thanks for reporting. I'm not quite sure how to fix this. If you have any ideas please let us know.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [henrik.k...@gmail.com](https://code.google.com/u/101552491294560837468/) on November 21, 2012 09:33:11_

I've managed to get this to work. You have to create a SSLSocketFactory with both a keystore and a truststore. I added this method to AuthConfig:

	public void certificate( String certURL, String password, String trustURL, String trustPassword ) 
			throws GeneralSecurityException, IOException {
		
		KeyStore keyStore = KeyStore.getInstance( KeyStore.getDefaultType() );
        InputStream jksStream = new URL(certURL).openStream();
        try {
        	keyStore.load( jksStream, password.toCharArray() );
        } finally { jksStream.close(); }

		KeyStore trustStore = KeyStore.getInstance( KeyStore.getDefaultType() );
        jksStream = new URL(trustURL).openStream();
        try {
        	trustStore.load( jksStream, trustPassword.toCharArray() );
        } finally { jksStream.close(); }
                
        SSLSocketFactory ssl = new SSLSocketFactory(keyStore, password, trustStore);
        ssl.setHostnameVerifier( SSLSocketFactory.STRICT_HOSTNAME_VERIFIER );
        
        builder.getClient().getConnectionManager().getSchemeRegistry()
        	.register( new Scheme("https", ssl, 443) );
	}

I now changed the beforeClass() method like this:
	@BeforeClass
	public static void beforeClass() throws Exception {
		final CertAuthWithTrustStoreScheme scheme = new CertAuthWithTrustStoreScheme();
        scheme.setCertURL(AbstractExternalServicesFunctionalTestCase.class.getClassLoader().getResource("client.jks").toString());
        scheme.setPassword("xdr537");
        scheme.setTrustURL(AbstractExternalServicesFunctionalTestCase.class.getClassLoader().getResource("trust.jks").toString());
        scheme.setTrustPassword("changeit");
        RestAssured.authentication = scheme;
		RestAssured.baseURI = "https://localhost/";
		RestAssured.port = 443;
	}

The best would be if you could use the keystore set by RestAssured.keystore(), but I didn't found a way to do that...

**Attachment:** [CertAuthWithTrustStoreScheme.groovy AuthConfig.java](http://code.google.com/p/rest-assured/issues/detail?id=205#hc2)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 22, 2012 12:57:10_

Thanks a lot for your help! I'll look into your code as soon as I find some time.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 27, 2012 23:29:16_

I've look into this briefly. I think there may be some overlap with the new AuthConfig method and features that's already available in Rest Assured. Have a look at Rest Assured.setKeystore and you'll find the similarities if you dig further into the code (see KeystoreSpecImpl). What may be missing is the possibility to set a trust url. Perhaps that's what missing and in that case we wouldn't need a new auth config method?

**Comment by johanhaleby** [comment]
_From [henrik.k...@gmail.com](https://code.google.com/u/101552491294560837468/) on January 23, 2013 05:42:16_

You already have an overlap then using the current AuthConfig.certificate() method because the SSLSocketFactory created by KeystoreSpecImpl isn't used if RestAssured.authentication is set to CertAuthScheme. I you extend KeystoreSpecImpl to set both cert and trust store, I think you should remove AuthConfig.certificate() and CertAuthScheme so this only can be configured in one way.

But I think the best solution would be to set the trust store as today with RestAssured.setKeyStore() (maybe renamed to setTruststore()) and make AuthConfig look if a keystore is set by setKeyStore() and use it the creating the SSLSocketFactory.

I also found that the port is hardcoded in AuthConfig.certificate() to 443. Shouldn't this be read from RestAssured.port?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 23, 2013 06:06:11_

I'm really really busy right now and it would be really helpful if you would like help out by creating a pull request at github for this. 

It sounds very strange that the port should not be hard-coded, that's probably a bug as well.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 19, 2013 00:17:55_

Some links: http://stackoverflow.com/questions/7256955/java-sslexception-hostname-in-certificate-didnt-match http://javaskeleton.blogspot.com/2010/07/avoiding-peer-not-authenticated-with.html http://tech.chitgoks.com/2011/04/24/how-to-avoid-javax-net-ssl-sslpeerunverifiedexception-peer-not-authenticated-problem-using-apache-httpclient/

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 23, 2013 10:39:44_

Thanks to Ian Forsey this should now be fixed:

RequestSpecBuilder request = ...
    request.setKeystore("truststore.jks", "password");

    CertAuthScheme scheme = new CertAuthScheme();
    scheme.setCertURL("clientcert.p12");
    scheme.setCertType("pkcs12");
    scheme.setPassword("password");
    scheme.setPort(8443);
    request.setAuthentication(scheme);

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 23, 2013 11:06:03_

You can also do:

given().auth().certificate("clientcert.p12",  "password", "pkcs12", 8443, scheme). ..

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on April 23, 2013 11:09:58_

That should be given().auth().certificate("clientcert.p12",  "password", "pkcs12", 8443, trustStore)

**Comment by johanhaleby** [comment]
_From [henrik.k...@gmail.com](https://code.google.com/u/101552491294560837468/) on May 08, 2013 01:46:07_

Great! When will this be available in a released version?
I also saw that the default port in CertAuthScheme was 433 instead of 443...

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 08, 2013 06:10:47_

Thanks for pointing out, I've changed it to 443. 

I don't know when the release will be available in Maven central but I've published a new snapshot version to Sonatype if you want to try it out. Depend on version 1.8.1-SNAPSHOT after having added the following maven repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on May 08, 2013 06:11:07_

**Status:** Fixed

**Comment by leonardjohn** [comment]
this help me a lot. #
