### ISSUE TITLE
Support for JSonBuilder in RequestSpecification.body method

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#398]
_From [corinnek...@gmail.com](https://code.google.com/u/115252170034907237047/) on June 06, 2013 18:35:47_

I guess it more an enhancement but it would be nice to be hable to do:

        JsonBuilder json = new JsonBuilder()
        json {
            name "myname"
            description "mydesc"
        }

        def request = testSpec.getRequestSpecification()
                .contentType("application/json")
                .header("Accept", "application/json")
                .body(json)
Any plan on it?

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=244_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 06, 2013 22:40:28_

Well I don't have any plans to implement it at the moment since REST Assured is supposed to be a  Java project so first off all your code wouldn't compile and secondly RA would have to expose parts of the Groovy API. 

I can totally see the benefits of this if you're using Groovy though. Perhaps you could create a Groovy extendo method and add that to the RA API which then converts the JsonBuilder to a string or something which is sent to RA.

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [scm.bl...@gmail.com](https://code.google.com/u/113463413954140258478/) on June 06, 2013 23:45:10_

Hi,
This will work 

JsonBuilder json = new JsonBuilder()
def request = testSpec.getRequestSpecification()
                .contentType("application/json")
                .header("Accept", "application/json")
                .body(json  {
                  name "MyApp"
                  description  "awesome app"
                  }
                )

You can also pass it as a map : 
.body(["name":"ddd", description:"ddd"])

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on June 06, 2013 23:46:19_

Cool I didn't know this!

**Comment by johanhaleby** [comment]
_From [corinnek...@gmail.com](https://code.google.com/u/115252170034907237047/) on June 06, 2013 23:55:03_

Really wierd the syntax proposed by Sebastien will work but if changed to:

        JsonBuilder json = new JsonBuilder()
        json  {
            name "MyApp"
            description  "awesome app"
        }
        def request = testSpec.getRequestSpecification()
                .contentType("application/json")
                .header("Accept", "application/json")
                .body(json)

I got:

com.jayway.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
	at com.jayway.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:830)
	at com.jayway.restassured.path.json.JsonPath$1.doParseWith(JsonPath.java:752)
	at com.jayway.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:871)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:182)
	at org.aerogear.pushee.tests.RegisterMobileVariantsSpecification.Registering a push application(RegisterMobileVariantsSpecification.groovy:72)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
	at groovy.json.JsonLexer.nextToken(JsonLexer.java:82)
	at com.jayway.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:92)
	at com.jayway.restassured.path.json.JsonPath$1$1.method(JsonPath.java:754)
	at com.jayway.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:828)
	... 4 more

**Comment by johanhaleby** [comment]
_From [karel.pi...@gmail.com](https://code.google.com/u/112976143100224772101/) on June 07, 2013 00:00:10_

If I understand that correctly, calling json { foo "bar"} directly in build() method API will return a Map, that RestAssured understands.

However, calling it first, then passing json object to build() will return JsonBuilder, which will call body(Object) and this is something RESTAssured has no bindings for.

**Comment by johanhaleby** [comment]
_From [corinnek...@gmail.com](https://code.google.com/u/115252170034907237047/) on June 07, 2013 00:07:55_

Very well found Karel, indeed something like
.body(json.toString())
will also work

It's a confusing one, would be nice to have a JsonBuilder support...
