### ISSUE TITLE
Getting ResponseParseException "No such field: CONTENT_TYPE" when getting JSON response without content-type header

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#407]
_From [fila...@gmail.com](https://code.google.com/u/100953504275866446270/) on August 06, 2013 07:38:53_

What steps will reproduce the problem? 1. Add RestAssured.defaultParser = Parser.JSON; since response does not contain content-type header
2. Send get request
		given().
		.header("X-Accept-Version", "2.0")
		.expect().statusCode(200)
		.when().get("/catalog"); What is the expected output? What do you see instead? I expect to get success on the test. The response contains JSON object. 

Actual result - getting following exception even though I have all the dependencies from the zip file in place and recreated test project from scratch using only supplied jars. Without setting default parser I'm getting just warning "WARNING: Could not parse content-type: Response does not have a content-type header".

Aug 05, 2013 10:27:24 PM com.jayway.restassured.internal.http.HTTPBuilder parseResponse
WARNING: Could not parse content-type: No such field: CONTENT_TYPE for class: com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder
FAILED: getCatalog
com.jayway.restassured.internal.http.ResponseParseException: OK
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:1400)
	at com.jayway.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:490)
	at com.jayway.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:439)
	at com.jayway.restassured.internal.http.HTTPBuilder$request.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:953)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendHttpRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendHttpRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:820)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$sendRequest.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.filter.RootFilter.filter(RootFilter.groovy:30)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:758)
	at com.jayway.restassured.internal.RequestSpecificationImpl$invokeFilterChain.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1142)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
	at com.jayway.restassured.internal.RequestSpecificationImpl$this$2$applyPathParamsAndSendRequest.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.get(RequestSpecificationImpl.groovy:131)
	at com.jayway.restassured.specification.RequestSender$get.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.get(ResponseSpecificationImpl.groovy:226)
	at motif.qa.rest.assured.GetExample.getCatalog(GetExample.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(...

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=253_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on October 08, 2013 22:10:48_

Hi, 

I don't suppose you could try out the same thing when you're using the Maven instead to see if you get the same error?

Regards,
/Johan

**Comment by johanhaleby** [comment]
_From [bonfante...@gmail.com](https://code.google.com/u/111293611306319474890/) on November 05, 2013 18:12:21_

Same problem here. Version 1.8.1 with Maven and Intellij...

given().header("Content-Type", "text/plain")

(trying setting manually the header, because the
given().contentType(ContentType.TEXT)
not add the content-type header in the request...)

**Comment by johanhaleby** [comment]
_From [bonfante...@gmail.com](https://code.google.com/u/111293611306319474890/) on November 06, 2013 06:55:54_

Digging in the source code, seems the rest-assured try to "survive" if the server doesn't provide a content-type for the response. 
I've verified the response of my jersey-server and noticed the missing content-type (specifically while mapping an exception).
Adding the content-type header in the response avoid this exception.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 11, 2013 23:28:55_

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 12, 2013 02:07:50_

I've now spent 3 hours trying to make Jersey send a response without a content type so that I can verify the error. How do you manage to get Jersey to do this?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 12, 2013 02:16:01_

I've also tried to provide a fix, but I haven't been able to test it so please verify that it works by building Rest Assured from the latest master.

**Comment by johanhaleby** [comment]
_From [bonfante...@gmail.com](https://code.google.com/u/111293611306319474890/) on November 12, 2013 03:40:33_

I'm with jersey 2.3.1 mapping an exception something like this: http://howtodoinjava.com/2013/06/03/exception-handling-in-jax-rs-resteasy-with-exceptionmapper/ .
Jersey didn't set the content-type automatically in this case, so I've set the header response manually. Maybe an updated jersey version behave differently... I don't know.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 12, 2013 06:48:59_

I've uploaded a new snapshot version to sonatype now, please depend on 1.8.2-SNAPSHOT after having added the following maven repo to see if it works:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>

**Comment by johanhaleby** [comment]
_From [bonfante...@gmail.com](https://code.google.com/u/111293611306319474890/) on November 12, 2013 09:11:12_

Thanks, I'll give a try when I can.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 14, 2013 01:09:54_

I'll consider this fixed, please re-open if you experience the same problem (please try to test it asap since I want to make a new release soon).

**Status:** Fixed
