### ISSUE TITLE
how to set the http timeout with restassured

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#409]
_From [zhouchen...@gmail.com](https://code.google.com/u/110038474376471617267/) on August 29, 2013 22:05:12_

Looking for the way to set the http timeout and keep the connection alive until finished getting complete response. What steps will reproduce the problem? 1. send the request
2. the service has around 1 second delay of the response
3. try to get the response body from the response
(the response body not so large)
the issue happens randomly What is the expected output? What do you see instead? randomly getting: 
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 4683; received: 4187
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:184)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:138)
	at com.jayway.restassured.internal.support.CloseHTTPClientConnectionInputStreamWrapper.read(CloseHTTPClientConnectionInputStreamWrapper.java:49)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader. read1 (BufferedReader.java:205)
	at java.io.BufferedReader.read(BufferedReader.java:279)
	at java.io.Reader.read(Reader.java:140)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1928)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1907)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1884)
	at org.apache.commons.io.IOUtils.toString(IOUtils.java:746) What version of the product are you using? On what operating system? 1.7.2 restassured on linux red hat 4.1.2-46 Please provide any additional information below.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=255_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on September 03, 2013 07:20:44_

Perhaps you can use the HttpClientConfig or ConnectionConfig in Rest Assured, see https://code.google.com/p/rest-assured/wiki/Usage#Detailed_configuration for more info.

Note: I'm marking this as a "invalid" since it's a question. Please use the mailing list for asking questions.

**Status:** Invalid

**Comment by babaravi** [comment]
Very simple way.
doc = Jsoup.connect(API_url).timeout(2000).get();

Here API_url is your API URL
