### ISSUE TITLE
rest-assured tries to connect to port 8080?

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#444]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on December 13, 2013 23:37:27_

Hi,

I'm trying to upgrade to 2.1.0 to get the namespaceContext fix (thanks for that!).

I have a simple test:

resp = return given().auth().digest(username, password).head("http://localhost:8002/...");

I get this stack trace:

org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8080 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:190)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
	at org.apache.http.client.HttpClient$execute$0.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl$RestAssuredHttpBuilder.doRequest(RequestSpecificationImpl.groovy:1654)
	at com.jayway.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:481)
	at com.jayway.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:430)
	at com.jayway.restassured.internal.http.HTTPBuilder$request$2.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1112)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendHttpRequest(RequestSpecificationImpl.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:730)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:965)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$sendRequest(RequestSpecificationImpl.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:730)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:128)
	at com.jayway.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:31)
	at com.jayway.restassured.filter.Filter$filter.call(Unknown Source)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.filter.FilterContext$next.call(Unknown Source)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:846)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:730)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1312)
	at com.jayway.restassured.internal.RequestSpecificationImpl.this$2$applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1085)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:909)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:730)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeMethod(RequestSpecificationImpl.groovy)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.call(PogoInterceptableSite.java:45)
	at org.codehaus.groovy.runtime.callsite.PogoInterceptableSite.callCurrent(PogoInterceptableSite.java:55)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:149)
	at com.jayway.restassured.internal.RequestSpecificationImpl.head(RequestSpecificationImpl.groovy:147)
	at PackageCreateTests.packageExists(PackageCreateTests.java:239)
	at PackageCreateTests.setup(PackageCreateTests.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	a...

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=290_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 20, 2013 00:41:10_

Looks like a bug! As a work-around try setting the port statically  (RestAssured.port = 8002) or perhaps try to use given().port(8002) and see if that works.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 20, 2013 00:51:53_

I cannot reproduce this. Could you please provide some more info?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 28, 2013 07:08:49_

Closing because no response from user

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on January 09, 2014 13:49:24_

Sorry for the delay. I finally got the time to work through it. My mistake was attempting to do this:

    private static final String BASE = "http://localhost:8002/manage/v2/packages";
    ...
    req.head("{BASE}/{pkgname}", BASE, packageName);

But it's pretty clear that applyPathParmasAndEncodePath() doesn't support having the base URI parts in parameters that way. Ultimately getTargetPath(path) returns "http://localhost:8080

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 09, 2014 23:12:16_

Thanks, I'll look into it when I get the opportunity.

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 18, 2014 09:16:47_

I thought about this some more and I actually don't think I ought to implement this because it leads to inconsistencies. Perhaps you have an API that expects a call to http://localhost:8080 with a path param to a URI. For example (JAX-RS):

@GET
@Path("/{uri}/{pkgname}");
public String x(..) {}

Now REST Assured should be able to send the following:

get("{uri}/{pkgname}", "http://localhost:8002/manage/v2/packages "packageName"). ..

Which means that the URI must be URL encoded as a parameter. So your example is really a special case and I think you should just do like this:

req.head(BASE + "/{pkgname}", packageName);

or:

RestAssured.baseURI = BASE;
req.head("/{pkgname}", packageName);

**Status:** WontFix

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on January 28, 2014 10:18:18_

Sure, that's fine. I do think it's worth documenting somewhere that what I tried won't work. Finding it by debugging the Groovy library that does the substitution was a little, uh, tedious ;-)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 28, 2014 11:08:18_

Probably a good idea :) You're very welcome to help out and submit a pull request.

**Comment by johanhaleby** [comment]
_From [normanwalsh](https://code.google.com/u/normanwalsh/) on January 28, 2014 11:13:19_

Touche. I'll put it on my todo list.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on January 28, 2014 11:29:55_

:)

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 21, 2014 02:07:26_

Issue 313 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 21, 2014 02:08:11_

Issue 313 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 21, 2014 02:08:51_

Issue 313 has been merged into this issue.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on February 21, 2014 02:09:39_

Issue 313 has been merged into this issue.

**Comment by mohamedb** [comment]
Still get the issue, explicitly setting the port (...when().port(80)....) seems to work

**Comment by johanhaleby** [comment]
Would you mind elaborating? What does your test look like? Are you using the latest version?

**Comment by mohamedb** [comment]
I'm using v: 3.0.2 , with Serenity v:1.1.38my, my test looks like: 
`
given().auth().preemptive().basic(AppConsts.USERNAME, AppConsts.PASSWORD).when()  
	.contentType(ContentType.JSON)

	.body(data).log().all()
	.post(URL)
	.then().log().all()
	.statusCode(HttpStatus.OK_200)
	.extract()
	.jsonPath();`
The URL= http://localhost/my_site/page.abc
The tested app is running on Apache2 using default port 80.

- If I add .port(80) it's working as expected on localhost
- If I keep the .port(80) on the same app, but deployed to a distant server (same port) it throws errors: `Unrecognized SSL message, plaintext connection?`

**Comment by johanhaleby** [comment]
And what's the URL?
