### ISSUE TITLE
ClassLoader issue with fge's json-schema-validator v.2.1.8

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#471]
_From [nema.nik...@gmail.com](https://code.google.com/u/115838758993113778750/) on March 04, 2014 11:51:41_

What steps will reproduce the problem? 1. Include newest (com.github.fge) json-schema-validator v.2.1.8 in compile scope.
2. Include (com.jayway.restassured) json-schema-validator v.2.3.0 in test scope. What is the expected output? What do you see instead? Expected normal functioning (as with 2.1.7). Instead see:
java.lang.NoClassDefFoundError: Lcom/github/fge/jsonschema/report/ProcessingReport;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.lang.Class.getDeclaredFields(Unknown Source)
        etc...

The problem is that package structure in v.2.1.8 has been changed (com/github/fge/jsonschema/report/ProcessingReport changed to
com/github/fge/jsonschema/core/report/ProcessingReport).

Please, update your json-schema-validator.
Regards,
Vitalii.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=316_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 04, 2014 07:13:35_

Seems quite strange to change package structure in a minor release. I've updated to 2.1.8 now and pushed to master.

**Status:** Fixed

**Comment by johanhaleby** [comment]
_From [nema.nik...@gmail.com](https://code.google.com/u/115838758993113778750/) on March 04, 2014 07:27:43_

And what is the newest version? Nothing changed with same 2.3.0.
I've removed library in my local maven repository before experimenting.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 04, 2014 09:59:44_

What do you mean? I've pushed the fix to the master branch at github, I haven't created a new release.

**Comment by johanhaleby** [comment]
_From [nema.nik...@gmail.com](https://code.google.com/u/115838758993113778750/) on March 04, 2014 13:36:09_

Ok, thanks a lot.

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 04, 2014 23:19:39_

If you want to try it out you need to depend on version 2.3.1-SNAPSHOT after having added the following Maven repo:

\<repositories>
        \<repository>
            \<id>sonatype</id>
            \<url> https://oss.sonatype.org/content/repositories/snapshots/</url> \<snapshots />
        \</repository>
\</repositories>
