### ISSUE TITLE
Not able to use JSON Path for json attributes having space

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#531]
_From [rpan...@gmail.com](https://code.google.com/u/111546879205986393799/) on November 28, 2014 10:51:52_

What steps will reproduce the problem? I have a json in following format where the json property 'All Categories' has a space in the middle:
{
  "All Categories": {
 
    "color": "#0adc00",
    "name": "Category Main",
    "data": [
      {

        "color": "#00dc00",
        "name": "Sub Category 1",
        "comments": 13,
        "data": [
          {
 
            "color": "#00dc00",
            "name": "Sub Sub Category",
            "comments": 8,
 
          },
 ],
       
        "tagColor": "0X00dc00"
      },
 ],
    "comments": 59,
    "tagColor": "0X0adc00"
  },
 }
}

When i use the following json path expression in my code to get the data nodes
[All Categories].data 

Following exception is shown:
\-----------------------------

java.lang.IllegalArgumentException: Invalid JSON expression:
Script1.groovy: 1: unexpected token: [ @ line 1, column 27.
                            [All Categories].data
                             ^

1 error

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:57)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:32)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath.getList(JsonPath.java:363)

\---------------------------------------------------------------------------------
I also tried with following JSON Path expression which also didn't work:
All Categories.data 

Exception thrown for this instance is
\---------------------------------------------------------------------------------
java.lang.IllegalArgumentException: The parameter "Categories" was used but not defined. Define parameters using the JsonPath.params(...) function
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:194)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getAsJsonObject(JSONAssertion.groovy:54)
	at com.jayway.restassured.internal.path.json.JSONAssertion$getAsJsonObject.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:141)
	at com.jayway.restassured.internal.path.json.JSONAssertion.getResult(JSONAssertion.groovy:32)
	at com.jayway.restassured.path.json.JsonPath.get(JsonPath.java:202)
	at com.jayway.restassured.path.json.JsonPath.getList(JsonPath.java:363)
\---------------------------------------------------------------------------------

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=376_

**Comment by johanhaleby** [comment]
_From [rpan...@gmail.com](https://code.google.com/u/111546879205986393799/) on November 28, 2014 01:57:34_

By using "\"All Categories\".data" i am able to get the nodes. This solution was given in https://code.google.com/p/rest-assured/issues/detail?id=318

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on November 29, 2014 00:54:52_

Yeah you need to escape the path if they contains space. It's a bit more readable if you use single quotes:

"'All Categories'.data"

**Status:** Invalid

**Comment by pdurbin** [comment]
@johanhaleby the single quote trick was very helpful to find. I just looked at https://github.com/rest-assured/rest-assured/wiki/Usage and didn't see it. Is it documented somewhere? Thanks!

**Comment by johanhaleby** [comment]
It's a part of the GPath "specification". You can read more about it [here](http://docs.groovy-lang.org/latest/html/documentation/index.html#gpath_expressions).

**Comment by pdurbin** [comment]
@johanhaleby ok. I don't see anything in there about the single quote trick but thanks.

**Comment by johanhaleby** [comment]
Ok. Maybe you could help out improving the docs? If you write something here in the comment I can include in the docs.

**Comment by rahulmittal14** [comment]
Case: String result = response.then().extract().path("CourseList[*].CourseName");

Error2: nvalid JSON expression: Script1.groovy: 1: unexpected token: ] @ line 1, column 39. CourseList[*].CourseName ^

1 error

When using "*", "?" , "@".. etc then getting same error. Please let me help to solve it.

**Comment by rakeshmishra361** [comment]
> Case: String result = response.then().extract().path("CourseList[*].CourseName");
> 
> Error2: nvalid JSON expression: Script1.groovy: 1: unexpected token: ] @ line 1, column 39. CourseList[*].CourseName ^
> 
> 1 error
> 
> When using "*", "?" , "@".. etc then getting same error. Please let me help to solve it.

Did you get any solution for this, When I manually verified using JSONPath expression tester tool, it's giving me proper output however when I am using XPath with a wildcard character, it's giving me same error what you are getting.

**Comment by rakeshmishra361** [comment]
> > Case: String result = response.then().extract().path("CourseList[*].CourseName");
> > Error2: nvalid JSON expression: Script1.groovy: 1: unexpected token: ] @ line 1, column 39. CourseList[*].CourseName ^
> > 1 error
> > When using "*", "?" , "@".. etc then getting same error. Please let me help to solve it.
> 
> Did you get any solution for this, When I manually verified using JSONPath expression tester tool, it's giving me proper output however when I am using XPath with a wildcard character, it's giving me same error what you are getting.



> Case: String result = response.then().extract().path("CourseList[*].CourseName");
> 
> Error2: nvalid JSON expression: Script1.groovy: 1: unexpected token: ] @ line 1, column 39. CourseList[*].CourseName ^
> 
> 1 error
> 
> When using "*", "?" , "@".. etc then getting same error. Please let me help to solve it.

Did you get any solution for this, When I manually verified using JSONPath expression tester tool, it's giving me proper output however when I am using XPath with a wildcard character, it's giving me same error what you are getting.

**Comment by rakeshmishra361** [comment]
> Case: String result = response.then().extract().path("CourseList[*].CourseName");
> 
> Error2: nvalid JSON expression: Script1.groovy: 1: unexpected token: ] @ line 1, column 39. CourseList[*].CourseName ^
> 
> 1 error
> 
> When using "*", "?" , "@".. etc then getting same error. Please let me help to solve it.

Did you get any solution for this, When I manually verified using JSONPath expression tester tool, it's giving me proper output however when I am using XPath with a wildcard character, it's giving me same error what you are getting.

**Comment by johanhaleby** [comment]
JsonPath in REST Assured is not using the json-path syntax. JsonPath in rest assured was created before the json-path "standard" (at least before an implementation was available in Java) and is using GPath. See examples [here](https://github.com/rest-assured/rest-assured/wiki/Usage#json-example).

**Comment by rakeshmishra361** [comment]
> JsonPath in REST Assured is not using the json-path syntax. JsonPath in rest assured was created before the json-path "standard" (at least before an implementation was available in Java) and is using GPath. See examples [here](https://github.com/rest-assured/rest-assured/wiki/Usage#json-example).

I am trying to validate JSON response by using RestAssured with wildcard character, however, getting below error
+++++++++++++++++++++++++++
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 1: unexpected token: *. @ line 1, column 44.
   onRootObject.ApplicationData.*.Id
+++++++++++++++++++++++++++

JSON Response data -
====================
{
"ApplicationData" :
   {
    "Tag1": {
      "Id": "Tag1Value",
      "Rate": 4.682119205298013,
      "Name": "Room"
    },
    "Tag2": {
      "Id": "Tag2Value",
      "Rate": 4.504854368932039,
      "Label": "Car"
    },
    "Tag3": {
      "Id": "Tag3Value",
      "Rate": 4.816326530612245,
      "Label": "Hotel"
    }
   }
}

=========================
**Submitted request with GET method: and saved response in response variable**

List getTagValue = response.getBody().path("ApplicationData.*.Rate");
double Rate = Double.parseDouble(getTagValue.get(0).toString());
Assert.assertEquals(Rate, 4.682119205298013);

Could you please help me to resolve this to get "Rate" tag value for all Tag ( Tag1, Tag2, and Tag3)

Thanks,
Rakesh Mishra

**Comment by johanhaleby** [comment]
Just use "ApplicationData.Rate" to get a list of all rate's.
