### ISSUE TITLE
Usint with Android

### ISSUE THREAD

**Issue by johanhaleby** [jayway/rest-assured#547]
_From [ti.vel...@gmail.com](https://code.google.com/u/110635181226820856404/) on March 09, 2015 14:39:03_

What steps will reproduce the problem? 1. Using with Android 2. 3. What is the expected output? What do you see instead? I get an exception:
 java.lang.NoClassDefFoundError: java.beans.PropertyDescriptor
            at libcore.reflect.InternalNames.getClass(InternalNames.java:55)
            at libcore.reflect.InternalNames.getClass(InternalNames.java:30)
            at java.lang.Class.getDexCacheType(Class.java:479) What version of the product are you using? On what operating system? 2.4.0 Please provide any additional information below. Sorry if this isn't meant to work with android.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=392_

**Comment by johanhaleby** [comment]
_From [ti.vel...@gmail.com](https://code.google.com/u/110635181226820856404/) on March 09, 2015 09:38:18_

Sorry for the typo on the title

Perhaps using Openbeans instead?

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 16, 2015 03:49:56_

**Status:** WontFix
