### ISSUE TITLE
Missing Content-type "text/uri-list" - as string results in IllegalArgumentException

### ISSUE THREAD

**Issue by rotmajster** [jayway/rest-assured#574]
Hi,
Im trying to tets some spring data rest api, but put method is somehow no go for me.
I want to submit something like this command, which works in commandline (or some browser addon):
curl -v -X PUT -H "Content-Type: text/uri-list" -d "http://localhost:8080/rest/timedefinition/10" http://localhost:8080/rest/rules/70/timedefinition

ContentType in Restassured does not contain "text/uri-list" (why? common in rest put methods), so I used just it's string value. I have command like this:
given().contentType("text/uri-list").body("http://localhost:8080/rest/timedefinition/10").put("http://localhost:8080/rest/rules/70/timedefinition")
but I always get this error:

java.lang.IllegalArgumentException: Don't know how to encode http://localhost:8080/rest/timedefinition/10 as a byte stream
	at com.jayway.restassured.internal.http.EncoderRegistry.encodeStream(EncoderRegistry.java:130)
	at groovy.lang.Closure.call(Closure.java:423)
	at com.jayway.restassured.internal.http.HTTPBuilder$RequestConfigDelegate.setBody(HTTPBuilder.java:1078)
	at com.jayway.restassured.internal.http.HTTPBuilder$RequestConfigDelegate.setBody(HTTPBuilder.java:1061)
	at groovy.lang.Closure.setPropertyTryThese(Closure.java:388)
	at groovy.lang.Closure.setPropertyDelegateFirst(Closure.java:378)
	at groovy.lang.Closure.setProperty(Closure.java:359)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest_closure21(RequestSpecificationImpl.groovy:1275)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at com.jayway.restassured.internal.http.HTTPBuilder.doRequest(HTTPBuilder.java:480)
	at com.jayway.restassured.internal.http.HTTPBuilder.request(HTTPBuilder.java:431)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendHttpRequest(RequestSpecificationImpl.groovy:1269)
	at com.jayway.restassured.internal.RequestSpecificationImpl.sendRequest(RequestSpecificationImpl.groovy:1108)
	at com.jayway.restassured.internal.filter.SendRequestFilter.filter(SendRequestFilter.groovy:31)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.filter.log.StatusCodeBasedLoggingFilter.filter(StatusCodeBasedLoggingFilter.java:94)
	at com.jayway.restassured.filter.log.ResponseLoggingFilter.filter(ResponseLoggingFilter.java:31)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.filter.log.RequestLoggingFilter.filter(RequestLoggingFilter.java:101)
	at com.jayway.restassured.internal.filter.FilterContextImpl.next(FilterContextImpl.groovy:49)
	at com.jayway.restassured.internal.RequestSpecificationImpl.invokeFilterChain(RequestSpecificationImpl.groovy:978)
	at com.jayway.restassured.internal.RequestSpecificationImpl.applyPathParamsAndSendRequest(RequestSpecificationImpl.groovy:1436)
	at com.jayway.restassured.internal.RequestSpecificationImpl.put(RequestSpecificationImpl.groovy:158)

Can anybody tell me, what is wrong with my code? Thx.

**Comment by johanhaleby** [comment]
The reason is the REST Assured doesn't recognise "text/uri-list" and it doesn't know how to encode the content since it's presumed to be binary. I think that this ought to work though in your case so I'm going to mark it as a bug.

Thanks for reporting!

**Comment by rotmajster** [comment]
Great, thx bro. Looking forward for this to be fixed.

**Comment by johanhaleby** [comment]
This has now been fixed in master
