### ISSUE TITLE
Android support?

### ISSUE THREAD

**Issue by bootstraponline** [jayway/rest-assured#583]
Are there plans to make rest-assured work with android?

I see:

```
java.lang.NoSuchFieldError: No static field DEF_CONTENT_CHARSET of type Ljava/nio/charset/Charset; in class Lorg/apache/http/protocol/HTTP; or its superclasses (declaration of 'org.apache.http.protocol.HTTP' appears in /system/framework/ext.jar)
at com.jayway.restassured.config.EncoderConfig.<init>(EncoderConfig.java:53)
at com.jayway.restassured.config.RestAssuredConfig.<init>(RestAssuredConfig.java:41)
at com.jayway.restassured.RestAssured.<clinit>(RestAssured.java:423)
at com.example.android.testing.uiautomator.BasicSample.HelloTest.pingServer(HelloTest.java:19)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:54)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:228)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

```

**Comment by johanhaleby** [comment]
I have personally no plans on making it work on Android but if anyone is interested in contributing I would gladly accept a pull request. Are you willing to help out?

**Comment by bootstraponline** [comment]
How do I build the rest-assured full jar to see if my patch worked? I don't see the build instructions documented anywhere. `mvn package` did something but I don't see any distribution zips and `mvn_release.sh` asks about gpg keys.

**Comment by johanhaleby** [comment]
Just do `mvn clean install` and all tests should pass. Then all artifacts are copied to your local maven repo. Run `mvn clean install -Prelease` to geneate source code, javadoc and all distribution zip files (they will be located in the `dist` folder)

**Comment by bootstraponline** [comment]
I installed it to my local maven repo then tried to compile. I'm always getting a `com.android.dex.DexIndexOverflowException`

OkHttp + hamcrest matchers is working for me on Android so I'll just stay with that.

**Comment by johanhaleby** [comment]
Ok thanks for trying

**Comment by drptbl** [comment]
@bootstraponline did the same thing to overcome this.
