### ISSUE TITLE
Wiki typo under "Create JSON from a HashMap" and related bug

### ISSUE THREAD

**Issue by vikramvi** [jayway/rest-assured#626]
Map<String, Object>  jsonAsMap = new HashMap<>();
map.put("firstName", "John");
map.put("lastName", "Doe");

In this map should be changed to jsonAsMap

Also with version 2.8.0 , am getting error as mentioned in https://code.google.com/p/rest-assured/issues/detail?id=206

Thanks,
Vikram

**Comment by johanhaleby** [comment]
> Also with version 2.8.0 , am getting error as mentioned in https://code.google.com/p/rest-assured/issues/detail?id=206

What error do you mean exactly? What does your test looks like?

**Comment by vikramvi** [comment]
@Test
	public void createList(){
		Map<String, Object>  jsonAsMap = new HashMap<>();
		jsonAsMap.put("title", "ECLIPSE-list");
		
		
		given().headers("X-Access-Token","xxxxx07236415e5afa181211fdd37e4074c9a936ef28cad07913xxxx",
				"X-Client-ID","b1e84f01bc7b80f0f482").
			    contentType("application/json; charset=utf-8").	
			    body(jsonAsMap).
			    //body("{\"title\":\"ECLIPSE-list-1111\"}").
	    when().
               post("https://a.wunderlist.com/api/v1/lists").
        then().
               statusCode(201);
	}

error as below

java.lang.IllegalStateException: Cannot serialize object because no JSON serializer found in classpath. Please put either Jackson or Gson in the classpath.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.mapping.ObjectMapping.serialize(ObjectMapping.groovy:136)
	at com.jayway.restassured.internal.mapping.ObjectMapping$serialize.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.jayway.restassured.internal.RequestSpecificationImpl.body(RequestSpecificationImpl.groovy:704)
	at com.vikramvi.wlapi.junit.WLApi.createList(WLApi.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by johanhaleby** [comment]
Please read the [docs](https://github.com/jayway/rest-assured/wiki/Usage#object-mapping), you need for example jackson-databind in your classpath.

**Comment by vikramvi** [comment]
Thanks johanhaleby , have added below and got it working

<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.5.0</version>
</dependency>

**Comment by johanhaleby** [comment]
I'll improve the docs
