### ISSUE TITLE
Can't create List<Node> object when list contains one element

### ISSUE THREAD

**Issue by BadNews87** [jayway/rest-assured#637]
When I create an xmlPath from the rest-assured String response and the try to create a List of Nodes I get an exception if the List contains only one element.

`List<Node> nodeList = xmlPath.getList("commentary.messages.period.message", Node.class);`

This should give me a List with exactly one element but instead I get an Exception

`Cannot convert class java.lang.String to interface com.jayway.restassured.path.xml.element.Node.
java.lang.ClassCastException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.path.ObjectConverter.convertObjectTo(ObjectConverter.groovy:54)
	at com.jayway.restassured.path.xml.XmlPath.convertObjectTo(XmlPath.java:913)
	at com.jayway.restassured.path.xml.XmlPath.getAsList(XmlPath.java:879)
	at com.jayway.restassured.path.xml.XmlPath.getList(XmlPath.java:348)
	at com.performgroup.usbasketballbackend.sprint26.USBask382Test.checkPlayerMainEventWithQualifierMessagesComments(USBask382Test.java:125)
`
When I have 2 elements I do not get this exception. Please fix this issue.

**Comment by BadNews87** [comment]
Version used 2.8.0

**Comment by johanhaleby** [comment]
What does your JSON look like?

**Comment by BadNews87** [comment]
It's actually an XML

Below is the xml structure and if there is one message node it doesn't create a list with one element.

`<commentary xmlns:basketballdata="www.nba.com">
  <matchInfo>
    <description>Oklahoma City Thunder vs Houston Rockets</description>
    <sport id="456">basketball</sport>
    <competition id="1" name="NBA">
    <country id="123" name="USA"/>
    </competition>
  </matchInfo>
  <messages>
    <period id="1">
      <message id="123" homeScore="0" awayScore="0"/>
    </period>
  </messages>
</commentary>`

But if I have 2 message nodes it creates a list with 2 elements.

`<commentary xmlns:basketballdata="www.nba.com">
  <matchInfo>
    <description>Oklahoma City Thunder vs Houston Rockets</description>
    <sport id="456">basketball</sport>
    <competition id="1" name="NBA">
    <country id="123" name="USA"/>
    </competition>
  </matchInfo>
  <messages>
    <period id="1">
      <message id="123" homeScore="0" awayScore="0"/>
      <message id="456" homeScore="2" awayScore="0"/>
    </period>
  </messages>
</commentary>`

**Comment by nolexa** [comment]
The node list conversion code has some odd logic in `xml-path-2.8.0-sources.jar!/com/jayway/restassured/assertion/XMLAssertion.groovy`. Here's the method:

```groovy
    private def toJavaObject(nodes, isAttributes, forceList) {
        if (nodes.size() == 1 && !hasChildren(nodes, isAttributes)) {
            return nodes.text()
        } else {
            return toJavaList(nodes, isAttributes, forceList)
        }
    }
```

When the input list consist of exactly one element with no children, this element is converted to a `String`. Hence the `Cannot convert class java.lang.String to interface com.jayway.restassured.path.xml.element.Node` error.

**Comment by johanhaleby** [comment]
That looks strange to me too. I suspect that this is a bug.

**Comment by BadNews87** [comment]
So in this case, can I expect this will be fixed?

**Comment by nolexa** [comment]
It does not seem that easy to be fixed. This is not a random bug, it looks like flawed design of `XmlPath`. If I change the node list conversion so that it will return a `Node` for a single node, a whole bunch of tests fail.

**Comment by nolexa** [comment]
@BadNews87 you can work around the problem so far. I answered your question on SO.

**Comment by johanhaleby** [comment]
Yes, I can't really remember why I've designed it that way so I'm sure
tests will fail. But that doesn't mean we can't fix it, I don't think many
people are extracting "Nodes" from XmlPath. We should be consistent with
how XmlSlurper behaves in Groovy. It will probably be a breaking change
though.

**Comment by BadNews87** [comment]
@nolexa thank you for the workaround....I was originally aiming for the attributes anyway. The bug remains relevant though. If you want to operate on nodes you're still not able to create List<Node> object with one element.

**Comment by johanhaleby** [comment]
I begun working on this but it's impossible to solve in its current implementation. XmlPath is tuned for  verifying "body expectations" when using the REST Assured DSL (`then().body("x.y", equalTo("z")`). The problems is that when using it with the REST Assured DSL you never want to validate against "Node" objects but rather the values (toString()) if the node (which is much more natural in this context imo). I think that in order to fix this we need two different modes in XmlPath, something like `STRICT` (which should be default) and something like `FUZZY` (used by the REST Assured DSL by default. Better naming suggestions are welcome). So when doing `new XmlPath()` you'll get `STRICT` which is probably what you would expect when returning values but with the ability to supply `FUZZY` as a configuration detail to be compatible with how its used in validation in RA DSL. Does that sound like a decent approach?
