### ISSUE TITLE
Number in .body is not matching BigDecimal operand.

### ISSUE THREAD

**Issue by JDKoder** [jayway/rest-assured#694]
Version 2.3.3 and verified also exists in latest 2.9 release

I'm using the ValidateableResponse in order to assert that a key returns as expected.  According to the wiki, I should be able to configure the JSON to return BigDecimal numbers with this code 
`RestAssured.config = newConfig().jsonConfig(jsonConfig().numberReturnType(NumberReturnType.BIG_DECIMAL))`

when I go to validate a response like so

`response.root("properties")
                .body("key", equalTo(new BigDecimal(evaluationKey)))`

where evaluation key is a String = "275", the assertion will fail with this message:

> java.lang.AssertionError: 1 expectation failed.
> JSON path properties.key doesn't match.
> Expected: <275>
>   Actual: 275

```
Some helpful pieces of the stack:

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
	at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.content(ResponseSpecificationImpl.groovy:251)
	at com.jayway.restassured.specification.ResponseSpecification$content$1.callCurrent(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at com.jayway.restassured.internal.ResponseSpecificationImpl.body(ResponseSpecificationImpl.groovy:234)
	at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.body(ValidatableResponseOptionsImpl.java:264)
```
The matcher seems to be receiving an Integer from the JSON response instead of a BigDecimal.

**Comment by johanhaleby** [comment]
Could you give me an example of what the JSON looks like?

**Comment by JDKoder** [comment]
the brackets are artifacts from Advanced REST client.  This is returned when I hit the rest URI and get a valid response back.

{
"class": [1]
0:  "SomeResource"
-
"properties": {
"$siren4j.class": "com.somepackage.SomeResource"
"key": 69
"type": "FOO_TYPE"
"started": false
"startDate": "01/04/2016"
"endDate": "12/29/2016"
"EmployeeIdentifier": "FOOEMPID"
"State": "NOT_STARTED"
}-
"entities": [...1]-
"links": [...3]-
}

**Comment by JDKoder** [comment]
Using version 2.3.3.  I'll see about updating to the current version to check if the problem goes away.

**Comment by johanhaleby** [comment]
This is only applicable for non-integers, see javadoc:

```java
/**
     * Specifies what kind of numbers to return
     */
    public enum NumberReturnType {
        /**
         * Convert all non-integer numbers to floats and doubles (depending on the size of the number)
         */
        FLOAT_AND_DOUBLE,
        /**
         * Convert all non-integer numbers to BigDecimal
         */
        BIG_DECIMAL,
        /**
         * Convert all non-integer numbers to doubles
         */
        DOUBLE
    }
```

So it works as expected. There's no way to force integers / longs to be converted automatically to BigDecimal today. You could add this as a feature request if you like.

**Comment by timrsfo** [comment]
I have a very similar issue and I'm wondering if I have the same problem or if my configuration is off.
My value is decimal not integer. I'm using rest-assured 3.1.0

code:

    RestAssured.config =   
    newConfig().jsonConfig(jsonConfig().numberReturnType(NumberReturnType.BIG_DECIMAL)); // (A) config
	given()
            .param("location", "37.7995242,-122.4091472")
            .param("key", apiKey)
            .param("radius", "500")
            .when()
            .get("nearbysearch/json")
            .then()
            .assertThat()
              .statusCode(200)
              .contentType(ContentType.JSON)
              .and()
              .body("results[0].geometry.location.lat", is(closeTo(37.7749295, 0.5)));  // (B) is closeTo
    //              .body("results[0].geometry.location.lat", is(37.7749295));  //  (C) is`

json response: 

    {
    "html_attributions": [],
    "next_page_token": "Cq...",
    "results": [
        {
            "geometry": {
                "location": {
                    "lat": 37.7749295,
                    "lng": -122.4194155
                },

output: 
// Combination (A) & (B), BIG_DECIMAL with isClose

    Exception in thread "main" java.lang.AssertionError: 1 expectation failed.
    JSON path results[0].geometry.location.lat doesn't match.
    Expected: is a numeric value within <0.5> of <37.7749295>
      Actual: 37.7749295
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
    	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
    	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
    	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
    	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)

output:  (A) with (C),  config BIG_DECIMAL, with is

    Exception in thread "main" java.lang.AssertionError: 1 expectation failed.
    JSON path results[0].geometry.location.lat doesn't match.
    Expected: is <37.7749295>
      Actual: 37.7749295
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    
    output:  No (A) with (B)  , no config with isClose
    
    Exception in thread "main" java.lang.AssertionError: 1 expectation failed.
    JSON path results[0].geometry.location.lat doesn't match.
    Expected: is a numeric value within <0.5> of <37.7749295>
      Actual: 37.77493
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    


Ouput:  No (A) with (C) , no config with is()

    Exception in thread "main" java.lang.AssertionError: 1 expectation failed.
    JSON path results[0].geometry.location.lat doesn't match.
    Expected: is <37.7749295>
      Actual: 37.77493
    
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)     

Is this part of an unresolved issue, or is there a fix for this? 
Thanks

**Comment by JDKoder** [comment]
I think this might just be a case where you aren't converting your expected value into a BigDecimal.  Remember that you are forcing all decimal numbers to BigDecimal which does not play nicely with normal primitives.

eg.  If you tried this:
 BigDecimal aBigDecimal = new BigDecimal("37.7749295");
 System.out.println(aBigDecimal.equals(37.7749295)); //prints false

because <Object> == <primitive> produces an error.

If you convert the argument to a big decimal first

BigDecimal aBigDecimal = new BigDecimal("37.7749295");
System.out.println(aBigDecimal.equals(new BigDecimal("37.7749295"))); //prints true

 try replacing is(37.7749295) (C) with is(equalTo(new BigDecimal("37.7749295"))).

**Comment by timrsfo** [comment]
@JDKoder  Thanks, that did it!

    import io.restassured.RestAssured;
    import io.restassured.http.ContentType;
    import io.restassured.path.json.config.JsonPathConfig.NumberReturnType;
    import static io.restassured.config.RestAssuredConfig.newConfig;
    import static io.restassured.config.JsonConfig.jsonConfig;
    
     @Test
      public void oneTest() {
          RestAssured.config =   
    	      newConfig().jsonConfig(jsonConfig().numberReturnType(NumberReturnType.BIG_DECIMAL));
        given()
          .param("location", "37.7995242,-122.4091472")
          .param("key", apiKey)
          .param("radius", "500")
        .when()
          .get("nearbysearch/json")
        .then()
          .assertThat()
            .statusCode(200)
          .and()
            .contentType(ContentType.JSON)
          .and()
           .body("results[0].geometry.location.lat", is(new BigDecimal("37.7749295"))); 
      }

**Comment by JDKoder** [comment]
Glad to help; thank you for letting us know the solution.

**Comment by ayush-finix** [comment]
I know this is old, but I wanted to point out that the correct way to compare BigDecimals is with the comparesEqualTo matcher, and in general, is with the compareTo method instead of equals.
